config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'boards#index'

  resources :boards do
    resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, {presence: true, length: {minimum: 3}}
  validates :title, {length: {maximum: 50}}
  validates :content, {presence: true, length: {minimum: 3}}
  validates :content, {length: {maximum: 140}}

  belongs_to :user
  has_many :tasks, dependent: :destroy

  def author_name
    user.display_name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}

  belongs_to :user
  belongs_to :task
end

app/models/profile.rb
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar
end

app/models/task.rb
class Task < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, {presence: true, length: {minimum: 3}}
  validates :title, {length: {maximum: 50}}
  validates :content, {presence: true, length: {minimum: 10}}
  validates :content, {length: {maximum: 400}}
  validates :expiration, presence: true

  has_many :comments, dependent: :destroy

  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  delegate :gender, :introduction, to: :profile, allow_nil: true

  def has_written?(board)
    boards.exists?(id: board.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'user.svg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def forbid_unuser
    if !user_signed_in?
      redirect_to new_user_session_path, notice: 'You need to sign in'
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :forbid_unuser, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path, notice: 'successfully saved a board!'
    else
      flash.now[:error] = 'failed to save'
      render :new
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to root_path, notice: 'successfully updated a board!'
    else
      flash.now[:error] = 'failed to update'
      render :edit
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy!
    redirect_to root_path, notice: 'successfully deleted a board!'
  end

  private
  def authenticate_user
    board = Board.find(params[:id])
    if current_user.id != board.user_id
      redirect_to root_path, notice: 'You don\'t have right'
    end
  end

  def board_params
    params.require(:board).permit(:title, :content)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :forbid_unuser, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user_comment, only: [:edit, :update, :destroy]

  def show
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    @comment = task.comments.find(params[:id])
  end

  def new
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    @comment = task.comments.build
  end

  def create
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    @comment = task.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to board_task_path(board, task), notice: 'successfully saved a comment!'
    else
      flash.now[:error] = 'failed to save'
      render :new
    end
  end

  def edit
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    @comment = task.comments.find(params[:id])
  end

  def update
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    @comment = task.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to board_task_path(board, task), notice: 'successfully updated a comment!'
    else
      flash.now[:error] = 'failed to update'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    comment = task.comments.find(params[:id])
    comment.destroy!
    redirect_to board_task_path(board, task), notice: 'successfully deleted a comment!'
  end

  private
  def authenticate_user_comment
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:task_id])
    comment = task.comments.find(params[:id])
    if current_user.id != comment.user_id
      redirect_to board_task_comment_path(board, task, comment), notice: 'You don\'t have right'
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :forbid_unuser

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)

    if @profile.save
      redirect_to profile_path, notice: 'successfully updated your profile!'
    else
      flash.now[:error] = 'failed to update'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :avatar
    )
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :forbid_unuser, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user_task, only: [:edit, :update, :destroy]

  def show
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
  end

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    @task.user_id = current_user.id

    if @task.save
      redirect_to board_path(board), notice: 'successfully saved a task!'
    else
      flash.now[:error] = 'failed to save'
      render :new
    end
  end

  def edit
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
  end

  def update
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to board_task_path(board, @task), notice: 'successfully updated a task!'
    else
      flash.now[:error] = 'failed to update'
      render :edit
    end
  end

  def destroy
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    @task.destroy!
    redirect_to board_path(board), notice: 'successfully deleted a task!'
  end

  private
  def authenticate_user_task
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    if current_user.id != task.user_id
      redirect_to board_task_path(board, task), notice: 'You don\'t have right'
    end
  end

  def task_params
    params.require(:task).permit(
      :title,
      :content,
      :expiration,
      :eyecatch
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<div class="box">
  <h2>Edit Board</h2>

  <% @board.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @board, local: true do |f| %>

    <div class="field">
      <label class="title">Name</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label class="content">Description</label>
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>
    
  <% end %>

</div>

app/views/boards/index.html.erb
<div class="box">
  <h2>All Boards</h2>
  <div class="boards">
    <% @boards.each do |board| %>
      <%= render 'commons/board', board: board %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <%= link_to '+ Add new board', new_board_path, class: 'new_board' %>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="box">
  <h2>New Board</h2>

  <% @board.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @board, local: true do |f| %>

    <div class="field">
      <label class="title">Name</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label class="content">Description</label>
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>
    
  <% end %>

</div>

app/views/boards/show.html.erb
<div class="box">
  <h2><%= @board.title %></h2>
  <div class="tasks">
    <% @board.tasks.each do |task| %>
      <%= link_to board_task_path(@board, task), class: 'task' do %>
        <% if task.eyecatch.attached? %>
          <%= image_tag task.eyecatch, class: 'task_eyecatch' %>
        <% end %>
        <h3 class="task_title"><%= task.title %></h3>
        <p class="task_content"><%= task.content %></p>
        <time class="task_by"><%= task.expiration %></time>
        <div class="task_display board_display">
          <%= image_tag task.user.avatar_image, class: 'task_display_icon board_display_icon' %>
          <p class="task_display_name board_display_name"><%= task.user.display_name %></p>
        </div>
        <div class="task_comment">
          <div class="task_comment_count"><%= task.comments.count %></div>
          <%= image_tag 'comment.svg', class: 'task_comment_icon' %>
        </div>
      <% end %>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to '+ Add new card', new_board_task_path(@board), class: 'new_task new_board' %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="box">
  <h2>Edit Comment</h2>

  <% @comment.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @comment, url: board_task_comment_path(@comment.task.board, @comment.task, @comment), method: :put, local: true do |f| %>

    <div class="field">
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>

  <% end %>

</div>

app/views/comments/new.html.erb
<div class="box">
  <h2>New Comment</h2>

  <% @comment.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @comment, url: board_task_comments_path(@comment.task.board, @comment.task, @comment), method: :post, local: true do |f| %>

    <div class="field">
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>

  <% end %>

</div>

app/views/comments/show.html.erb
<div class="box">
  <h2 class="comment_h">Comment</h2>
  <div class="comment_show">
    <%= image_tag @comment.user.avatar_image, class: 'comment_show_icon' %>
    <div class="comment_show_content">
      <div class="comment_show_content_name"><%= @comment.user.display_name %></div>
      <p class="comment_show_content_p"><%= @comment.content %></p>
    </div>
    <% if user_signed_in? && current_user.comments.exists?(id: @comment.id) %>
      <div class="board_drop comment_drop">
        <%= image_tag 'drop.svg', class: 'board_drop_icon comment_drop_icon' %>
        <div class="board_drop_content comment_drop_content">
          <%= link_to 'Edit', edit_board_task_comment_path(@comment.task.board, @comment.task, @comment), class: 'board_drop_content_btn comment_drop_content_btn' %>
          <%= link_to 'Delete', board_task_comment_path(@comment.task.board, @comment.task, @comment), class: 'board_drop_content_btn comment_drop_content_btn', method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/commons/_board.html.erb
<div class="board">
  <h3 class="board_title"><%= link_to board.title, board_path(board) %></h3>
  <p class="board_content"><%= board.content %></p>
  <div class="board_display">
    <%= image_tag board.user.avatar_image, class: 'board_display_icon' %>
    <p class="board_display_name"><%= board.author_name %></p>
  </div>
  <% if user_signed_in? && current_user.has_written?(board) %>
    <div class="board_drop">
      <%= image_tag 'drop.svg', class: 'board_drop_icon' %>
      <div class="board_drop_content">
        <%= link_to 'Edit', edit_board_path(board), class: 'board_drop_content_btn' %>
        <%= link_to 'Delete', board_path(board), class: 'board_drop_content_btn', method: :delete %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="box">
        <div class="header">
          <div class="header_title">
            <% if current_page?(root_path) %>
              <h1 class="header_title_h">Boards</h1>
            <% else %>
              <%= link_to :back, class: 'header_title_img' do %>
                <%= image_tag 'back.svg' %>
              <% end %>
              <%= link_to 'Boards', '/', class: 'header_title_h header_title_a' %>
            <% end %>
          </div>
          <% if user_signed_in? %>
            <div class="board_drop header_drop">
              <%= image_tag current_user.avatar_image, class: 'header_drop_icon' %>
              <div class="board_drop_content header_drop_content">
                <%= link_to 'Profile', profile_path, class: 'board_drop_content_btn' %>
                <%= link_to 'Sign out', destroy_user_session_path, data: {method: 'delete'}, class: 'board_drop_content_btn' %>
              </div>
            </div>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path, class: 'header_login' %>
          <% end %>
        </div>
      </div>
    </header>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="box">

  <% @profile.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <h2>Edit Profile</h2>

  <%= form_with model: @profile, url: profile_path, method: 'put', local: true do |f| %>

    <div class="field">
      <label class="avatar">Avatar</label>
      <%= f.file_field :avatar, class: 'image_input' %>
    </div>

    <div class="field">
      <label class="nickname">Name</label>
      <%= f.text_field :nickname %>
    </div>

    <div class="field">
      <label class="introduction">Introduction</label>
      <%= f.text_area :introduction %>
    </div>

    <div class="field">
      <label class="gender">Gender</label>
      <%= f.select :gender, ['male', 'female', 'other'] %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>

  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="box">
  <div class="profile">
    <div class="profile_img">
      <%= image_tag current_user.avatar_image %>
    </div>
    <div class="profile_info">
      <h3 class="profile_info_name"><%= current_user.display_name %></h3>
      <h4 class="profile_info_gender">・<%= current_user.gender %></h4>
      <p class="profile_info_introduction"><%= current_user.introduction %></p>
    </div>
    <%= link_to 'Edit', edit_profile_path, class: 'profile_edit' %>
  </div>

  <div class="boards">
    <% current_user.boards.each do |board| %>
      <%= render 'commons/board', board: board %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="box">
  <h2>Edit Task</h2>

  <% @task.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @task, url: board_task_path(@task.board, @task), method: :put, local: true do |f| %>

    <div class="field">
      <label class="eyecatch">Eyecatch</label>
      <%= f.file_field :eyecatch, class: 'image_input' %>
    </div>

    <div class="field">
      <label class="title">Name</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label class="content">Description</label>
      <%= f.text_area :content %>
    </div>

    <div class="field">
      <label class="expiration">Expiration</label>
      <%= f.date_field :expiration %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>
    
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="box">
  <h2>New Card</h2>

  <% @task.errors.full_messages.each do |message| %>
    <p class="error_message"><%= message %></p>
  <% end %>

  <%= form_with model: @task, url: board_tasks_path(@task.board), method: :post, local: true do |f| %>

    <div class="field">
      <label class="eyecatch">Eyecatch</label>
      <%= f.file_field :eyecatch, class: 'image_input' %>
    </div>

    <div class="field">
      <label class="title">Name</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label class="content">Description</label>
      <%= f.text_area :content %>
    </div>

    <div class="field">
      <label class="expiration">Expiration</label>
      <%= f.date_field :expiration %>
    </div>

    <div class="actions">
      <%= f.submit :Submit %>
    </div>
    
  <% end %>

</div>

app/views/tasks/show.html.erb
<div class="box">
  <div class="task_show">
    <div class="task_show_top">
      <h2><%= @task.title %></h2>
      <% if @task.eyecatch.attached? %>
        <%= image_tag @task.eyecatch, class: 'task_show_top_eyecatch' %>
      <% end %>
      <% if user_signed_in? && current_user.tasks.exists?(id: @task.id) %>
        <div class="board_drop task_top">
          <%= image_tag 'drop.svg', class: 'board_drop_icon task_top_icon' %>
          <div class="board_drop_content task_top_content">
            <%= link_to 'Edit', edit_board_task_path(@task.board, @task), class: 'board_drop_content_btn task_top_content_btn' %>
            <%= link_to 'Delete', board_task_path(@task.board, @task), class: 'board_drop_content_btn task_top_content_btn', method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="task_show_content">
      <p class="task_show_content_p"><%= @task.content %></p>
      <time class="task_show_content_date"><%= @task.expiration %></time>
    </div>
    <div class="comments">
      <h3>Comment</h3>
      <div class="comments_content">
        <% @task.comments.each do |comment| %>
          <%= link_to board_task_comment_path(@task.board, @task, comment), class: 'comment' do %>
            <%= image_tag comment.user.avatar_image, class: 'comment_icon' %>
            <div class="comment_content">
              <div class="comment_content_name"><%= comment.user.display_name %></div>
              <p class="comment_content_p"><%= comment.content %></p>
            </div>
          <% end %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= link_to '+ Add new comment', new_board_task_comment_path(@task.board, @task), class: 'comments_new new_board' %>
      <% end %>
    </div>
  </div>
</div>